// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./components/breadCrumb.vue')['default']
    Bred: typeof import('./components/breadCrumb.vue')['default']
    DasBoard: typeof import('./components/dashBoard/dashBoard.vue')['default']
    DashBoard: typeof import('./components/dashBoard/dashBoard.vue')['default']
    DefaultFooter: typeof import('./components/defaultFooter.vue')['default']
    Footer: typeof import('./components/footer.vue')['default']
    FullScreen: typeof import('./components/fullScreen.vue')['default']
    Github: typeof import('./components/Github.vue')['default']
    Grou: typeof import('./components/Login/Grou.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hero: typeof import('./components/Login/Hero.vue')['default']
    Login: typeof import('./components/Login/login.vue')['default']
    MySider: typeof import('./components/Sider.vue')['default']
    NavHeader: typeof import('./components/navHeader.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./components/Sider.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ToggleDarkTheme: typeof import('./components/toggleDarkTheme.vue')['default']
    ToggleScreen: typeof import('./components/toggleScreen.vue')['default']
    ToggleTheme: typeof import('./components/toggleDarkTheme.vue')['default']
    UserInfo: typeof import('./components/userInfo.vue')['default']
  }
}
